### ISSUE TITLE
Adwaita link cursor showing up instead of the link cursor provided by Posy's curors

### ISSUE THREAD

**Issue by Ryanics** [simtrami/posy-improved-cursor-linux#2]
I am using Nobara Linux 36, based on Fedora 36. I have KDE and the latest version of the frameworks. I am just installing the black cursor with the colorful waiting cursors, and I've also tried with the all in one package. I've tried installing directly from the kde "Get more cursors ui", as well as downloading directly from opendesktop.org/pling and installing the file from there. Everything works except the link cursor (the image that the cursor changes to when you are about to click on a link. It goes to the default adwaita one. I got the update for the cursors, going to the 1.4 update and it seemed to be fine, but all the link cursors except the one I was using were all the adwaita theme. And after the 1.5 update, they were all adwaita. Looking in the files, the link cursors seem to be in the correct place in the cursors folder (from the download from pling)  and named correctly, so I wonder if it's something with the theme file.

**Comment by simtrami** [comment]
Because my installation process was putting the cursor sets folders directly into my `~/.icons` directory, I renamed it to `.icons.old` and installed the cursor sets via KDE settings "Get more cursors ui...". 
I selected the "All cursor sets" file and immediately saw the previews were missing some cursors (see [screenshot](https://imgur.com/a/wAWgIrp)). I then activated the Posy's Cursor Black set, tested hovering on a link and saw the link cursor from the KDE Classic set instead of the Posy's one.

Comparing the content of `~/.icons/Posy_Cursor_Black/cursors/` with `~/.icons.old/Posy_Cursor_Black/cursors/`, I can see there is a new folder called `GNUSparseFile.0/` in the first one and it is filled with cursors files, including the buggy _link_ (see [screenshot](https://imgur.com/a/6d5DSgt)). These files were not simply copied into `GNUSparseFile.0/` during installation, they were misplaced and corrupted : moving them back in place did not fix anything and the files showed differences with the originals (not the same size, Dolphin does not recognize them as cursors).

A quick research gave me this on this weird `GNUSparseFile.0/` folder : https://www.gnu.org/software/tar/manual/html_section/Compression.html#sparse. However theses files have nothing special (such as _holes_) and they do not appear in this folder when I look into a freshly downloaded .tar.gz from opendsktop.org. Nor does this sparse folder appear when extracting the downloaded archive.

Can you observe this behavior on your PC when using the KDE settings "Get more cursors ui..." installation method?
Has cloning the repo into your `~/.icons` folder fixed it for you?

**Comment by Ryanics** [comment]
I'll check when I get home, thanks again for the quick reply. And yes, Adwaita is the default cursor theme for gnome and a lot of versions of linux. It's also the default theme for gnome.

**Comment by Ryanics** [comment]
Deleting that GNUSparseFile.0/ folder removes whatever cursor files I am messing with. After Looking, there are no link hand cursors in the files.
![hand icon missing](https://user-images.githubusercontent.com/97851858/187308377-7c95a5a0-85d5-47d5-bffb-c63e04f2983a.png)

**Comment by Ryanics** [comment]
Do you have an update on this? Please and thank you. If you need any other assistance, I wanna help in any way I can.

**Comment by simtrami** [comment]
Hi, sorry for not keeping you up to date, I had some busy days.

So you too have this `GNUSparseFile.0/` folder and the same cursors seem to be missing. I suspect KDE's "Get more cursors ui..." tool to be messing with my files somehow.
NB: I do not suspect opendesktop.org because when I download the archive directly from the website and decompress it into `~/.icons`, it works fine.

While I am trying to find a fix for this, I suggest you to git clone the repository directly into you `~/.icons` folder.

**Comment by Ryanics** [comment]
Thank you for the reply. And sorry for seeming like I am trying to rush, I am not. Anything I can do to help troubleshoot I will. (I've used these cursors on window and linux so they are kind of my favorite). I'll try manually installing them to the /.icons folder.

**Comment by simtrami** [comment]
This issue merges to #4, as it better represents the bug we're facing.
Also, I just uploaded the v1.6 to the store, it should be available soon.
I tried something new : the files are compressed with xz. Let's hope it repairs the install process :crossed_fingers:
